title: Sara Moreno · Developer Blog
description: Personal blog about SAP, cloud and architecture
url: https://sarawittel.github.io
lang: en

theme: minima

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginate_path: "/blog/page/:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
