title: Sara Moreno · Developer Blog
description: Personal blog with Jekyll and GitHub Pages
url: https://sarawittel.github.io

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
